apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      imagePullSecrets:
        - name: aws-registry-key
      containers:
        - name: ${APP_NAME}
          image:  856190518830.dkr.ecr.us-east-2.amazonaws.com/myapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
